name: verpa_mobile
description: Verpa - Smart Aquarium Management Mobile App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # HTTP & API
  dio: ^5.3.2
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # Storage & Cache
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  
  # UI & Design
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  lottie: ^2.6.0
  flutter_staggered_grid_view: ^0.7.0
  fl_chart: ^0.65.0
  
  # Navigation
  go_router: ^12.1.1
  
  # Authentication & Security
  flutter_secure_storage: ^9.0.0
  crypto: ^3.0.3
  
  # Device Features
  permission_handler: ^11.0.1
  device_info_plus: ^9.1.0
  package_info_plus: ^4.2.0
  local_auth: ^2.1.8
  
  # Push Notifications
  firebase_core: ^2.17.0
  firebase_messaging: ^14.7.3
  flutter_local_notifications: ^16.1.0
  
  # Image & Media
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  camera: ^0.10.5
  image: ^4.1.7
  
  # Utils
  intl: ^0.18.1
  url_launcher: ^6.2.1
  connectivity_plus: ^5.0.1
  mobile_scanner: ^4.0.1
  csv: ^6.0.0
  archive: ^3.4.10
  provider: ^6.1.2
  tflite_flutter: ^0.10.4
  flutter_slidable: ^3.1.0
  tutorial_coach_mark: ^1.2.11
  flutter_localizations:
    sdk: flutter
  
  # Voice Assistant
  speech_to_text: ^6.5.1
  flutter_tts: ^3.8.5
  
  # Real-time Collaboration
  web_socket_channel: ^2.4.0
  
  # Location Services
  geolocator: ^10.1.0
  
  # Development
  logger: ^2.0.2
  flutter_dotenv: ^5.1.0
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.7
  retrofit_generator: ^8.0.6
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  
  # Linting
  flutter_lints: ^3.0.1
  
  # Testing
  bloc_test: ^9.1.5
  mocktail: ^1.0.1
  
  # App Icons & Splash Screen
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.5

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/languages/
    - assets/models/
    - .env
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

# App Icons Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#1E88E5"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"
  min_sdk_android: 21

# Splash Screen Configuration
flutter_native_splash:
  color: "#1E88E5"
  image: "assets/images/splash_logo.png"
  android_12:
    image: "assets/images/splash_logo.png"
    color: "#1E88E5"
  ios_content_mode: center
  android_gravity: center
  fullscreen: true