export enum EquipmentType {
  FILTER = 'FILTER',
  HEATER = 'HEATER',
  LIGHTING = 'LIGHTING',
  PUMP = 'PUMP',
  SKIMMER = 'SKIMMER',
  CO2_SYSTEM = 'CO2_SYSTEM',
  UV_STERILIZER = 'UV_STERILIZER',
  CHILLER = 'CHILLER',
  WAVEMAKER = 'WAVEMAKER',
  AUTO_FEEDER = 'AUTO_FEEDER',
  DOSING_PUMP = 'DOSING_PUMP',
  OTHER = 'OTHER',
}